-- CMO Post Studio · runtime storage for editable trigger templates +
-- freeform tweet drafts generated via Claude. Admin-only at the RLS
-- layer; UI lives at /admin/cmo (CmoPreviewPage).

-- ── cmo_templates ────────────────────────────────────────────────────────
-- 5 trigger types with editable tweet copy templates. id is the
-- canonical trigger key (audit_complete · graduation · milestone ·
-- weekly_picks · early_spotter). The frontend keeps SVG share-card
-- design hardcoded in the React component for now; only the tweet
-- COPY field is admin-editable from this table. SVG slot editing
-- arrives in a follow-up.
CREATE TABLE IF NOT EXISTS public.cmo_templates (
  id            text PRIMARY KEY,
  label         text NOT NULL,
  copy_template text NOT NULL,
  fires_when    text NOT NULL,
  data_source   text NOT NULL,
  updated_at    timestamptz NOT NULL DEFAULT now(),
  updated_by    uuid REFERENCES public.members(id) ON DELETE SET NULL
);

ALTER TABLE public.cmo_templates ENABLE ROW LEVEL SECURITY;

-- Admin-only · the template surface is internal marketing config, not
-- a public-facing concept like rulebook copy.
DROP POLICY IF EXISTS "admins read cmo_templates"  ON public.cmo_templates;
DROP POLICY IF EXISTS "admins write cmo_templates" ON public.cmo_templates;
CREATE POLICY "admins read cmo_templates" ON public.cmo_templates FOR SELECT
  USING (EXISTS (SELECT 1 FROM public.members WHERE id = auth.uid() AND is_admin));
CREATE POLICY "admins write cmo_templates" ON public.cmo_templates FOR ALL
  USING (EXISTS (SELECT 1 FROM public.members WHERE id = auth.uid() AND is_admin))
  WITH CHECK (EXISTS (SELECT 1 FROM public.members WHERE id = auth.uid() AND is_admin));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.cmo_templates TO authenticated;
GRANT ALL ON public.cmo_templates TO service_role;

-- Seed the 5 trigger types with the copy from CmoPreviewPage.tsx v1.
-- ON CONFLICT DO NOTHING so reruns don't clobber edits.
INSERT INTO public.cmo_templates (id, label, copy_template, fires_when, data_source) VALUES
  ('audit_complete',
   '1. Audit complete',
   $$audited {project_name} ↓

↓ {top_concern_1}
↓ {top_concern_2}

↑ {top_strength_1}

{score}/100 · band: {band}

npx commitshow audit github.com/{owner}/{project_name}$$,
   'analysis_snapshots row inserted (initial · resubmit · weekly)',
   'project.project_name · score.total / band · concerns[0..1] · strengths[0]'),
  ('graduation',
   '2. Graduation',
   $${project_name} graduated {grade} · Season {season_id}.

shipped by @{creator_handle} — final score {score}/100, {cohort} cohort.

every commit, on stage.

commit.show/projects/{project_id}$$,
   'project.graduation_grade flips to Valedictorian / Honors / Graduate',
   'project.project_name · creator.x_handle · graduation_grade · season_id · final score'),
  ('milestone',
   '3. Milestone',
   $${project_name} just hit {milestone_label}.

ranked #{rank} in {category} · auditioning live in Season Zero.

{milestone_context}

commit.show/projects/{project_id}$$,
   'ladder_milestones row inserted (first_top_10 · streak_100_days · climb_100_steps · etc.)',
   'milestone_type · project.project_name · category · current rank'),
  ('weekly_picks',
   '4. Weekly Top Picks',
   $$this week in commit.show ↑

#1 {p1_name} · {p1_delta} pts · {p1_score}/100
#2 {p2_name} · {p2_delta} pts · {p2_score}/100
#3 {p3_name} · {p3_delta} pts · {p3_score}/100

every commit, on stage · commit.show/ladder$$,
   'cron · every Monday 9 AM PT (Peak A slot)',
   'top 3 score_total_delta over the past 7 days'),
  ('early_spotter',
   '5. Early Spotter (Scout hit)',
   $$@{scout_handle} spotted {project_name} {days_before} days before it graduated {grade}.

{scout_tier} Scout · early spotter hit #{hit_count} this season.

scouts who call it early get a permanent badge — that's the whole point of the tier.

commit.show/scouts/{scout_id}$$,
   'graduation event · scout had a correct Forecast > 7 days before',
   'scout.x_handle · scout.tier · project.project_name · days_before_graduation · final score')
ON CONFLICT (id) DO NOTHING;

-- ── cmo_drafts ─────────────────────────────────────────────────────────────
-- Freeform tweet drafts generated by M (Claude API via the
-- generate-tweet-copy Edge Function). Each row holds:
--   prompt           the freeform request from admin ("draft a launch tweet")
--   variations       jsonb [{copy, hashtags, rationale}, ...]
--   selected_index   int · which variation admin picked
--   status           draft → approved → posted → archived
CREATE TABLE IF NOT EXISTS public.cmo_drafts (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  prompt         text NOT NULL,
  variations     jsonb NOT NULL,
  selected_index int,
  status         text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'approved', 'posted', 'archived')),
  notes          text,
  created_at     timestamptz NOT NULL DEFAULT now(),
  created_by     uuid REFERENCES public.members(id) ON DELETE SET NULL,
  updated_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cmo_drafts_created_at ON public.cmo_drafts (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cmo_drafts_status     ON public.cmo_drafts (status, created_at DESC);

ALTER TABLE public.cmo_drafts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "admins read cmo_drafts"  ON public.cmo_drafts;
DROP POLICY IF EXISTS "admins write cmo_drafts" ON public.cmo_drafts;
CREATE POLICY "admins read cmo_drafts" ON public.cmo_drafts FOR SELECT
  USING (EXISTS (SELECT 1 FROM public.members WHERE id = auth.uid() AND is_admin));
CREATE POLICY "admins write cmo_drafts" ON public.cmo_drafts FOR ALL
  USING (EXISTS (SELECT 1 FROM public.members WHERE id = auth.uid() AND is_admin))
  WITH CHECK (EXISTS (SELECT 1 FROM public.members WHERE id = auth.uid() AND is_admin));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.cmo_drafts TO authenticated;
GRANT ALL ON public.cmo_drafts TO service_role;

-- Auto-update updated_at on UPDATE.
CREATE OR REPLACE FUNCTION public.cmo_set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;

DROP TRIGGER IF EXISTS trg_cmo_templates_updated_at ON public.cmo_templates;
CREATE TRIGGER trg_cmo_templates_updated_at BEFORE UPDATE ON public.cmo_templates
  FOR EACH ROW EXECUTE FUNCTION public.cmo_set_updated_at();

DROP TRIGGER IF EXISTS trg_cmo_drafts_updated_at ON public.cmo_drafts;
CREATE TRIGGER trg_cmo_drafts_updated_at BEFORE UPDATE ON public.cmo_drafts
  FOR EACH ROW EXECUTE FUNCTION public.cmo_set_updated_at();
